header:
  show_title: false
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-include-cache
  - jekyll-titles-from-headings
  
# Custom CSS
css: "https://chrisbutch.github.io/NJU-Cheminformatics-and-Modelling-2025/assets/custom.css"
